### PR TITLE
UI-73 - Check if ID is defined before opening the table details

### LINKED ISSUE #73: Gateway creation error
When creating a gateway configuration if you quickly go to gateway details after creating gateway sometimes bootstraping doesnt get done proper.

In addition to mentioned above if you try delete gateway that wasnt properly created and than create one with same name and MAC it will fail.

Steps:
Create gateway and quickly click on the details for the gateway ( before notification "Gateway succsefully bootstraped" ). Notice there is no BS Config ID.
Delete the created gateway noting name and MAC
Create gateway with same name and MAC, click on details, no bs config id

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #73

### CODE REVIEW

File: src/app/shared/details/details.component.ts [hunk 1]
```diff
@@ -15,6 +15,8 @@ export class DetailsComponent {
   ) { }
 
   onOpenDetailsPage() {
-    this.router.navigate([`${this.router.routerState.snapshot.url}/details/${this.value.id}`]);
+    if (this.value.id !== undefined) {
```
Comment (darkodraskovic) [inline src/app/shared/details/details.component.ts:18]: No need to test for inequality here, you can just do
```
if (this.value.id)
```

File: src/app/shared/details/details.component.ts [hunk 2]
```diff
@@ -15,6 +15,8 @@ export class DetailsComponent {
   ) { }
 
   onOpenDetailsPage() {
-    this.router.navigate([`${this.router.routerState.snapshot.url}/details/${this.value.id}`]);
```
Comment (darkodraskovic) [inline src/app/shared/details/details.component.ts:18]: A question, if `this.value.id` is actually undefined, where we'll we end up?
