### PR TITLE
140 - Add type edit/create to table and remove type undefined

### LINKED ISSUE #140: Fix entity (thing, channel) add bar
When adding things or channels
- remove grayed out option to add an ID (it's confusing otherwise),
- enable the user to enter type, i.e. de-gray an option or remove it (it's confusing otherwise),
- remove completely redundant `undefined` field bellow the magnifier.
- fix the broken type field

### PR DESCRIPTION
**Pull request by darkodraskovic**
Resolves #140 

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

### CODE REVIEW

File: src/app/pages/channels/channels.component.ts [hunk 1]
```diff
@@ -124,6 +125,22 @@ export class ChannelsComponent implements OnInit {
     // close edit row
     event.confirm.resolve();
 
+    const type = event.newData.type;
+    if (type) {
+      this.channelsService.getChannel(event.data.id).subscribe(
+        (channel: Channel) => {
+          event.newData.metadata = channel.metadata || {};
+          event.newData.metadata['type'] = type;
```
Comment (manuio) [inline src/app/pages/channels/channels.component.ts:133]: You can use event.newData.metadata.type = type

File: src/app/pages/channels/channels.component.ts [hunk 2]
```diff
@@ -112,6 +112,7 @@ export class ChannelsComponent implements OnInit {
     // close create row
     event.confirm.resolve();
 
+    event.newData.type && (event.newData.metadata = {'type': event.newData.type});
```
Comment (manuio) [inline src/app/pages/channels/channels.component.ts:115]: It would be more readable to use
```
const type = event.newData.type;
if (type) {
    event.newData.metadata = {'type': type});
}
```

**Review by manuio — CHANGES_REQUESTED** [review]

File: src/app/pages/channels/channels.component.ts (hunk 2 above)
Comment (darkodraskovic) [reply src/app/pages/channels/channels.component.ts:115]: This is a javascript/typescript idiom. Plus, we don't use redundant declaration/initialization.

**Review by manuio — APPROVED** [review]
LGTM

**Review by blokovi — APPROVED** [review]
